export const CATEGORIES = [
  { id: 'development', label: 'פיתוח תוכנה', icon: '💻' },
  { id: 'design', label: 'עיצוב גרפי', icon: '🎨' },
  { id: 'marketing', label: 'שיווק דיגיטלי', icon: '📣' },
  { id: 'content', label: 'כתיבת תוכן', icon: '✍️' },
  { id: 'video', label: 'וידאו ועריכה', icon: '🎬' },
  { id: 'data', label: 'דאטה ואנליטיקס', icon: '📊' },
  { id: 'devops', label: 'DevOps & Cloud', icon: '☁️' },
  { id: 'mobile', label: 'אפליקציות מובייל', icon: '📱' },
];

export const mockBots = [
  {
    id: '1',
    bot_type: 'freelancer',
    name: 'אורי כהן — Full Stack Dev',
    role: 'מפתח Full Stack בכיר',
    description: 'מתמחה ב-React, Node.js ו-PostgreSQL. בניתי יותר מ-50 מוצרים דיגיטליים עבור סטארטאפים וחברות גדולות.',
    skills: ['React', 'Node.js', 'PostgreSQL', 'TypeScript', 'AWS'],
    avatar_url: 'https://i.pravatar.cc/150?img=11',
    gallery_media: [
      'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400',
      'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400',
    ],
    is_published: true,
    rating: 4.9,
    total_orders: 127,
    category: 'development',
    pricing_basic: { price: 500, title: 'בסיסי', description: 'עמוד נחיתה פשוט', delivery_days: 3 },
    pricing_standard: { price: 1500, title: 'סטנדרטי', description: 'אפליקציה עם DB', delivery_days: 7 },
    pricing_premium: { price: 4000, title: 'פרמיום', description: 'מוצר מלא עם API', delivery_days: 14 },
    owner_email: 'uri@example.com',
    owner_name: 'אורי כהן',
    opening_message: 'שלום! אני אורי, מפתח Full Stack עם 8 שנות ניסיון. איך אוכל לעזור לך היום?',
    instructions: 'אתה סוכן AI שמייצג את אורי כהן, מפתח Full Stack. ענה על שאלות לגבי שירותי הפיתוח, מחירים, ולוחות זמנים.',
    quick_messages: ['מה המחירים שלך?', 'כמה זמן לוקח לבנות אפליקציה?', 'יש לך דוגמאות עבודה?'],
    portfolio: [
      { title: 'אפליקציית SaaS לניהול פרויקטים', description: 'בנייה מאפס של מוצר SaaS עם 500 משתמשים', image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400' },
      { title: 'פלטפורמת מסחר אלקטרוני', description: 'חנות אונליין עם אינטגרציית Stripe', image_url: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400' },
    ],
    reviews: [
      { reviewer: 'דנה לוי', rating: 5, text: 'עבודה מצוינת, מהיר ומקצועי!' },
      { reviewer: 'יוסי אבי', rating: 5, text: 'ממליץ בחום, תוצאה מדהימה' },
    ],
  },
  {
    id: '2',
    bot_type: 'freelancer',
    name: 'מאיה ברק — UX/UI Designer',
    role: 'מעצבת UX/UI',
    description: 'מעצבת ממשקי משתמש ב-Figma עם דגש על חוויית משתמש מעולה. עבדתי עם מוצרים עם מיליוני משתמשים.',
    skills: ['Figma', 'UI Design', 'UX Research', 'Prototyping', 'Design Systems'],
    avatar_url: 'https://i.pravatar.cc/150?img=5',
    gallery_media: [
      'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400',
      'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=400',
    ],
    is_published: true,
    rating: 4.8,
    total_orders: 89,
    category: 'design',
    pricing_basic: { price: 400, title: 'בסיסי', description: 'עיצוב 3 מסכים', delivery_days: 2 },
    pricing_standard: { price: 1200, title: 'סטנדרטי', description: 'עיצוב אפליקציה מלאה', delivery_days: 5 },
    pricing_premium: { price: 3500, title: 'פרמיום', description: 'Design System מלא', delivery_days: 10 },
    owner_email: 'maya@example.com',
    owner_name: 'מאיה ברק',
    opening_message: 'היי! אני מאיה, מעצבת UX/UI. ספרי לי על הפרויקט שלך ואראה מה אוכל לעשות עבורך.',
    instructions: 'אתה סוכן AI שמייצג את מאיה ברק, מעצבת UX/UI. עזור ללקוחות להבין את תהליך העיצוב, המחירים ולוחות הזמנים.',
    quick_messages: ['מה כלול בעיצוב בסיסי?', 'כמה זמן לוקח?', 'איך מתחילים?'],
    portfolio: [
      { title: 'אפליקציית פינטק', description: 'עיצוב מלא לאפליקציית ניהול כספים', image_url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400' },
    ],
    reviews: [
      { reviewer: 'ניר שלום', rating: 5, text: 'עיצוב מדהים, הלקוחות שלי אהבו!' },
    ],
  },
  {
    id: '3',
    bot_type: 'freelancer',
    name: 'תום אלון — Marketing Expert',
    role: 'מומחה שיווק דיגיטלי',
    description: 'מנהל קמפיינים ב-Google ו-Meta עם ROI מוכח. ניהלתי תקציבי פרסום של מיליונים.',
    skills: ['Google Ads', 'Meta Ads', 'SEO', 'Analytics', 'Growth Hacking'],
    avatar_url: 'https://i.pravatar.cc/150?img=33',
    gallery_media: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400',
    ],
    is_published: true,
    rating: 4.7,
    total_orders: 64,
    category: 'marketing',
    pricing_basic: { price: 800, title: 'בסיסי', description: 'הגדרת קמפיין', delivery_days: 3 },
    pricing_standard: { price: 2000, title: 'סטנדרטי', description: 'ניהול חודשי', delivery_days: 1 },
    pricing_premium: { price: 5000, title: 'פרמיום', description: 'ניהול מלא + אסטרטגיה', delivery_days: 1 },
    owner_email: 'tom@example.com',
    owner_name: 'תום אלון',
    opening_message: 'שלום! אני תום, מומחה שיווק דיגיטלי. מה הוא המטרה השיווקית שלך?',
    instructions: 'אתה סוכן AI שמייצג את תום אלון. עזור ללקוחות להבין אסטרטגיות שיווק, מחירים ויעדים.',
    quick_messages: ['מה ה-ROI הצפוי?', 'איזה פלטפורמה מומלץ?', 'כמה עולה לנהל קמפיין?'],
    portfolio: [],
    reviews: [],
  },
  {
    id: '4',
    bot_type: 'employer',
    name: 'TechStart IL',
    role: 'מפתח Full Stack',
    company_name: 'TechStart IL',
    job_title: 'Senior Full Stack Developer',
    job_description: 'אנחנו מחפשים מפתח Full Stack בכיר לצוות מוצר שלנו. תעבוד על מוצר SaaS עם מאות אלפי משתמשים.',
    skills: ['React', 'Node.js', 'AWS', 'PostgreSQL'],
    avatar_url: 'https://i.pravatar.cc/150?img=50',
    is_published: true,
    rating: 4.6,
    total_orders: 12,
    category: 'development',
    salary_range: '25,000 - 35,000 ₪',
    job_type: 'fulltime',
    location: 'תל אביב (היברידי)',
    owner_email: 'hr@techstart.co.il',
    owner_name: 'TechStart IL',
    opening_message: 'שלום! אני הבוט המראיין של TechStart. אשמח לשמוע עליך ועל הניסיון שלך.',
    instructions: 'אתה בוט ריאיון של TechStart. שאל את המועמד על ניסיון, פרויקטים ומוטיבציה.',
    interview_criteria: 'ניסיון מינימום 5 שנים ב-React ו-Node.js, ניסיון ב-AWS, יכולת עבודה בצוות.',
    interview_type: 'general',
    whatsapp_exposure: { mode: 'after_pass' },
    gallery_media: [],
  },
  {
    id: '5',
    bot_type: 'employer',
    name: 'Design Co.',
    role: 'מעצב UI/UX',
    company_name: 'Design Co.',
    job_title: 'UI/UX Designer',
    job_description: 'סטודיו עיצוב מחפש מעצב UI/UX יצירתי עם ניסיון במוצרים דיגיטליים.',
    skills: ['Figma', 'Adobe XD', 'Prototyping'],
    avatar_url: 'https://i.pravatar.cc/150?img=47',
    is_published: true,
    rating: 4.5,
    total_orders: 7,
    category: 'design',
    salary_range: '18,000 - 25,000 ₪',
    job_type: 'fulltime',
    location: 'הרצליה',
    owner_email: 'jobs@designco.co.il',
    owner_name: 'Design Co.',
    opening_message: 'היי! אני הבוט של Design Co. ספר לי על עצמך ועל ניסיון העיצוב שלך.',
    instructions: 'אתה בוט ריאיון של Design Co. שאל על ניסיון עיצוב, כלים ופורטפוליו.',
    interview_criteria: 'ניסיון מינימום 3 שנים ב-Figma, פורטפוליו חזק.',
    interview_type: 'general',
    whatsapp_exposure: { mode: 'after_pass' },
    gallery_media: [],
  },
];

export const mockOrders = [
  {
    id: 'ord1',
    bot_id: '1',
    bot_name: 'אורי כהן — Full Stack Dev',
    freelancer_email: 'uri@example.com',
    client_email: 'demo@jobly.co.il',
    tier: 'standard',
    price: 1500,
    status: 'in_progress',
    created_date: '2024-01-15',
    rating: null,
    review: null,
  },
  {
    id: 'ord2',
    bot_id: '2',
    bot_name: 'מאיה ברק — UX/UI Designer',
    freelancer_email: 'maya@example.com',
    client_email: 'demo@jobly.co.il',
    tier: 'basic',
    price: 400,
    status: 'completed',
    created_date: '2024-01-01',
    rating: 5,
    review: 'עבודה מדהימה!',
  },
];

export const mockUser = {
  id: 'user1',
  email: 'demo@jobly.co.il',
  full_name: 'ישראל ישראלי',
  role: 'admin',
  is_admin: true,
  user_type: 'freelancer',
  avatar_url: 'https://i.pravatar.cc/150?img=12',
  bio: 'פרילנסר עם ניסיון של 5 שנים בפיתוח ועיצוב',
  headline: 'Full Stack Developer & Designer',
  whatsapp: '0501234567',
};
